# Copyright (c) 2022 - 2026 Fraunhofer AISEC
# Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM debian:12

# copy checkc to image
RUN mkdir /checkc

COPY target/x86_64-unknown-linux-gnu/release/checkc /checkc/checkc
COPY scripts/podman/entrypoint_ref.sh /checkc/entrypoint_ref.sh

ENTRYPOINT ["/checkc/entrypoint_ref.sh"]

CMD ["/bin/bash", "-c", "sleep 20000000000"]
