// Copyright (c) 2022 - 2026 Fraunhofer AISEC
// Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package c_config.user_ns;

message Config {
  // uint32 uid = 1;
  // uint32 gid = 2;
  reserved 1 to 2;
  repeated IdMapping uid_map = 3;
  repeated IdMapping gid_map = 4;
  // true if no other user-ns with parent init-ns has the same mapping; see logs if false
  bool unique_mapping = 5;
}

message IdMapping {
  uint32 current = 1;
  uint32 parent = 2;
  uint32 range = 3;
}