// Copyright (c) 2022 - 2026 Fraunhofer AISEC
// Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::{Error, Result};

use libc;
use nix::errno::*;
use std::collections::{HashMap, HashSet};
use std::fs::*;
use std::hash::{Hash, Hasher};
use std::os::fd::{FromRawFd, IntoRawFd};
use std::os::linux::fs::MetadataExt;
use std::{fmt::Display, path::PathBuf};

// Generated by [`prost-build`]
include!(concat!(env!("OUT_DIR"), "/c_config.ns.rs"));
// Generated by [`pbjson-build`]
include!(concat!(env!("OUT_DIR"), "/c_config.ns.serde.rs"));

const NS_GET_USERNS: libc::c_ulong = 0xb701;
const NS_GET_PARENT: libc::c_ulong = 0xb702;
const _NS_GET_NSTYPE: libc::c_ulong = 0xb703;
const _NS_GET_OWNER_UID: libc::c_ulong = 0xb704;

pub type NsMap = HashMap<Type, Info>;

// a set of namespaces, each type may occur at most once
pub type NsSet = HashSet<Info>;

impl Display for Type {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Cgroup => write!(f, "cgroup"),
            Self::Ipc => write!(f, "ipc"),
            Self::Network => write!(f, "net"),
            Self::Mount => write!(f, "mnt"),
            Self::Pid => write!(f, "pid"),
            Self::Time => write!(f, "time"),
            Self::User => write!(f, "user"),
            Self::Uts => write!(f, "uts"),
            Self::Unspecified => write!(f, "UNSPECIFIED"),
        }
    }
}

// Allow parsing of clone flags
impl TryFrom<libc::c_int> for Type {
    type Error = Error;

    fn try_from(value: libc::c_int) -> std::result::Result<Self, Self::Error> {
        match value {
            libc::CLONE_NEWCGROUP => Ok(Self::Cgroup),
            libc::CLONE_NEWIPC => Ok(Self::Ipc),
            libc::CLONE_NEWNET => Ok(Self::Network),
            libc::CLONE_NEWNS => Ok(Self::Mount),
            libc::CLONE_NEWPID => Ok(Self::Pid),
            libc::CLONE_NEWUSER => Ok(Self::User),
            libc::CLONE_NEWUTS => Ok(Self::Uts),
            0x00000080 => Ok(Self::Time),
            unspecified => Err(Error::ConversionFailed(format!(
                "Unknown namespace flag ({unspecified})"
            ))),
        }
    }
}

impl Type {
    // get list of currently supported namespaces
    pub fn list() -> Vec<Type> {
        vec![
            Self::Cgroup,
            Self::Ipc,
            Self::Network,
            Self::Mount,
            Self::Pid,
            Self::User,
            Self::Uts,
            Self::Time,
        ]
    }
}

impl Hash for Info {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.r#type.hash(state)
    }
}

impl Eq for Info {}

impl Info {
    // return set of /proc/[pid]/ns entries
    pub fn parse_proc_ns(pid: libc::pid_t) -> Result<NsSet> {
        log::debug!("Retrieving contents of /proc/{pid}/ns");
        let mut ns_set = HashSet::new();
        for ns_type in Type::list() {
            ns_set.insert(Self::info_by_ns_type(pid, ns_type)?);
        }
        Ok(ns_set)
    }

    pub fn info_by_ns_type(pid: libc::pid_t, ns_type: Type) -> Result<Self> {
        let id = Id::from_type(pid, ns_type)?;
        let owner = ns_get_owner_user_ns(pid, ns_type)?;

        Ok(Self {
            r#type: ns_type.into(),
            id: Some(id),
            owner: Some(owner),
        })
    }
}

impl From<internal::Hierarchy> for Hierarchy {
    fn from(value: internal::Hierarchy) -> Self {
        let mut hierarchy = Self::default();
        hierarchy.parent = Some(value.parent_id);

        let children = value
            .children
            .iter()
            .to_owned()
            .map(|child| (*child).clone().into())
            .collect();
        hierarchy.children = children;

        hierarchy
    }
}

impl TryInto<internal::Hierarchy> for Hierarchy {
    type Error = Error;
    fn try_into(self) -> std::result::Result<internal::Hierarchy, Error> {
        if let Some(parent_id) = self.parent {
            let mut internal_hierarchy = internal::Hierarchy::new(parent_id);

            for child in self.children {
                let child_hierarchy = child.try_into()?;
                internal_hierarchy.children.insert(child_hierarchy);
            }

            return Ok(internal_hierarchy);
        }

        Err(Error::ConversionFailed(format!(
            "c_config::ns::hierarchy: field parent not set"
        )))
    }
}

mod internal {
    use super::{Id, Type};
    use crate::Result;
    use serde::{Deserialize, Serialize};
    use std::collections::HashSet;
    use std::fmt::Display;
    use std::hash::{Hash, Hasher};
    use std::path::PathBuf;
    // custom def of proto::Hierarchy in order to use HashSet instead of Vec
    #[derive(Debug, Clone, Serialize, Deserialize)]
    pub struct Hierarchy {
        pub parent_id: Id,
        pub children: HashSet<Hierarchy>,
    }

    impl Hash for Hierarchy {
        fn hash<H: Hasher>(&self, state: &mut H) {
            self.parent_id.hash(state);
        }
    }

    impl PartialEq for Hierarchy {
        fn eq(&self, other: &Self) -> bool {
            self.parent_id == other.parent_id
        }
    }

    impl Eq for Hierarchy {}

    impl Display for Hierarchy {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            self.display_helper(0, f)
        }
    }

    impl Hierarchy {
        fn display_helper(
            &self,
            level: usize,
            f: &mut std::fmt::Formatter<'_>,
        ) -> std::fmt::Result {
            f.write_fmt(format_args!(
                "{:indent$}[{}]\n",
                " ",
                self.parent_id.st_ino,
                indent = level * 4
            ))?;

            for child in &self.children {
                child.display_helper(level + 1, f)?;
            }

            Ok(())
        }

        pub fn new(parent_id: Id) -> Self {
            Self {
                parent_id,
                children: HashSet::new(),
            }
        }

        fn create_hierarchy(ns_type: Type) -> Result<Hierarchy> {
            let proc_dir = std::fs::read_dir("/proc")?;

            // read proc and filter for PID-directories
            let pids: Vec<PathBuf> = proc_dir
                .filter(std::result::Result::is_ok)
                .map(|entry| {
                    let entry = entry.unwrap();
                    entry.path()
                })
                .filter(|entry| entry.is_dir())
                .filter(|entry| {
                    entry
                        .to_str()
                        .unwrap()
                        .contains(|char: char| char.is_ascii_digit())
                })
                .collect();

            let pids = pids.iter().map(|entry| {
                entry
                    .file_name()
                    .unwrap()
                    .to_str()
                    .unwrap()
                    .parse::<libc::pid_t>()
                    .unwrap()
            });

            // for each pid get ns id and corresponding parent ns id
            let id_map: Vec<(Id, Id)> = pids
                .map(|pid| super::ns_get_parent_ns(pid, ns_type))
                .filter(Result::is_ok)
                .map(Result::unwrap)
                .flatten()
                .collect();
            // Identity mapping should be initial namespace
            let (root, _) = id_map
                .iter()
                .filter(|(p_id, id)| p_id == id)
                .next()
                .unwrap()
                .clone();

            let mut hierarchy = Self::new(root);
            hierarchy.populate(&id_map);

            Ok(hierarchy)
        }

        fn populate(&mut self, id_map: &[(Id, Id)]) {
            // remove parent_id from children
            let id_map_filtered: Vec<(Id, Id)> = id_map
                .iter()
                .copied()
                .filter(|(_, id)| id != &self.parent_id)
                .collect();

            // get children from map
            if !id_map_filtered.is_empty() {
                let mut children = HashSet::new();
                id_map_filtered
                    .iter()
                    .filter(|(parent_id, _)| parent_id == &self.parent_id)
                    .map(|mapping| mapping.1.to_owned())
                    .map(Self::new)
                    .for_each(|child| {
                        children.insert(child);
                    });

                // populate children
                let children = children
                    .drain()
                    .map(|mut child| {
                        child.populate(&id_map_filtered);
                        child
                    })
                    .collect();

                self.children = children;
            }
        }

        pub fn user_ns_hierarchy() -> Result<Hierarchy> {
            Self::create_hierarchy(Type::User)
        }

        pub fn pid_ns_hierarchy() -> Result<Hierarchy> {
            Self::create_hierarchy(Type::Pid)
        }
    }
}

pub fn ns_get_owner_user_ns(pid: libc::pid_t, ns_type: Type) -> Result<Id> {
    let path = format!("/proc/{pid}/ns/{}", ns_type.to_string());
    let path = PathBuf::from(path);

    let f_ns = File::open(path)?;
    let fd = f_ns.into_raw_fd();

    let owner_fd = unsafe { libc::ioctl(fd, NS_GET_USERNS) };
    if owner_fd == -1 {
        let errno = Errno::last();

        // special case: user namespace
        if errno == Errno::EPERM && ns_type == Type::User {
            let id = Id::from_fd(fd)?;
            let _ = unsafe { File::from_raw_fd(fd) };

            return Ok(id);
        }
        return Err(Error::IoctlFailed(errno));
    }

    let user_ns = unsafe { File::from_raw_fd(owner_fd) };
    let metadata = user_ns.metadata().unwrap();

    // claim ownership
    let _ = unsafe { File::from_raw_fd(fd) };

    Ok(Id {
        st_dev: metadata.st_dev(),
        st_ino: metadata.st_ino(),
    })
}

// returns list of (parent id, namespace id) for user or pid namespace of given process
pub fn ns_get_parent_ns(pid: libc::pid_t, ns_type: Type) -> Result<Vec<(Id, Id)>> {
    let path = format!("/proc/{pid}/ns/{}", ns_type.to_string());
    let path = PathBuf::from(path);
    let mut result = Vec::new();

    let f_ns = File::open(path)?;
    let mut fd = f_ns.into_raw_fd();
    let mut id = Id::from_fd(fd)?;

    let mut parent_fd = unsafe { libc::ioctl(fd, NS_GET_PARENT) };
    while parent_fd != -1 {
        let parent_id = Id::from_fd(parent_fd)?;

        result.push((parent_id, id));

        // recurse in next layer
        id = parent_id;
        // claim ownership of not longer needed fd
        let _ = unsafe { File::from_raw_fd(fd) };
        fd = parent_fd;
        // get parent of parent
        parent_fd = unsafe { libc::ioctl(fd, NS_GET_PARENT) };
    }

    // no new parent found
    match Errno::last() {
        // EPERM indicates initial namespace
        nix::errno::Errno::EPERM => result.push((id, id)),
        errno => return Err(Error::IoctlFailed(errno)),
    }

    // claim ownership
    let _ = unsafe { File::from_raw_fd(fd) };

    Ok(result)
}

pub fn ns_config(init_pid: libc::pid_t, c_init_pid: libc::pid_t) -> Result<Config> {
    let mut proto_ns_config = Config::default();

    // parse namespaces
    log::info!(
        "Collecting namespace config for host PID {init_pid} and container PID {c_init_pid}"
    );
    let ns_set_init = Info::parse_proc_ns(init_pid)?;
    let ns_set_c_init = Info::parse_proc_ns(c_init_pid)?;

    log::debug!("Computing shared namespaces between container and host");
    proto_ns_config.shared_host = ns_set_c_init
        .intersection(&ns_set_init)
        .map(|info| info.to_owned())
        .collect();

    log::debug!("Computing container namespaces not shared with host");
    proto_ns_config.unshared = ns_set_c_init
        .iter()
        .filter(|ns| !ns_set_init.contains(ns))
        .map(|info| info.to_owned())
        .collect();

    log::debug!("Computing hierarchies of user and pid namespaces");
    let user_hierarchy = internal::Hierarchy::user_ns_hierarchy()?;
    let pid_hierarchy = internal::Hierarchy::pid_ns_hierarchy()?;

    proto_ns_config.user_ns_hierarchy = Some(Hierarchy::from(user_hierarchy));
    proto_ns_config.pid_ns_hierarchy = Some(Hierarchy::from(pid_hierarchy));

    Ok(proto_ns_config)
}
