// Copyright (c) 2022 - 2026 Fraunhofer AISEC
// Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package evaluation;

import "c_config/ns.proto";
import "c_config/caps.proto";

message TestResult {
  bool passed = 2;
  bool valid = 3;
  repeated string info = 4;
}
message EvalInfo {
  repeated int32 pids_container = 1;
  repeated int32 pids_ref_container = 2;
  int32 pid_host = 3;
  string container_root_host = 4;
}

message EvalResult { 
  bool unprivileged = 1;
  map<string, Category> categories = 2;
  EvalInfo info = 3;
}

message Category {
  IsolationMechanisms isolation = 1;
  repeated c_config.caps.Capability capabilities = 2;
  map<string, TestResult> tests = 3;
  string description = 4;
}

message Namespaces { 
  repeated c_config.ns.Type active = 1; 
  repeated c_config.ns.Type desired = 2;
}

  message Chroot {
  bool chroot = 1;
  bool pivot_root = 2;
  }


message IsolationMechanisms {
  Namespaces namespaces = 1;
  Chroot chroot = 2;
  message Cgroup { bool cgroup = 1; }
  Cgroup cgroup = 3;
}
