// Copyright (c) 2022 - 2026 Fraunhofer AISEC
// Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use std::collections::{HashMap, HashSet};

use crate::c_config::*;
use once_cell::sync::Lazy;

pub mod cap_sec;

pub static FLAG_LOCATION_ALLOW: &'static [&'static str] = &[];

// regex
pub static MOUNTPOINT_FS_SKIPS: &'static [&'static str] = &[
    "proc",
    "sysfs",
    "devtmpfs",
    "devpts",
    "securityfs",
    "cgroup",
    "cgroup2",
    "pstore",
    "efivarfs",
    "bpf",
    "autofs",
    "mqueue",
    "hugetlbfs",
    "debugfs",
    "tracefs",
    "fusectl",
    "configfs",
    "binfmt_misc",
];

pub static MOUNTPOINT_PATH_SKIPS: &'static [&'static str] = &[];

pub static FLAG_SEARCH_PATH_SKIPS: &'static [&'static str] = &[];

// required cgroups controllers
pub static CGROUPS_CONTROLLERS_REQUIRED: &'static [i32] = &[];

// allowed devices (coarse)
pub static DEV_MAJOR_WHITELIST: Lazy<HashSet<(device::Type, u32)>> = Lazy::new(|| {
    use crate::c_config::device::Type;
    let mut set = HashSet::new();

    // Unix98 PTY slaves (automatically generated by devpts)
    for i in 136..=143 {
        set.insert((Type::Char, i));
    }

    set
});

// allowed devices in /dev and mknod
pub static DEV_WHITELIST_GENERAL: Lazy<HashMap<device::Id, device::Device>> = Lazy::new(|| {
    use crate::c_config::device::*;
    let mut map = HashMap::new();
    map.insert(
        Id {
            r#type: Type::Char as i32,
            major: 1,
            minor: 3,
        },
        Device {
            file: format!("/dev/null"),
            id: Some(Id {
                r#type: Type::Char as i32,
                major: 1,
                minor: 3,
            }),
            permissions: 0,
            user: 0,
            group: 0,
            read_access: true,
            write_access: true,
        },
    );
    map.insert(
        Id {
            r#type: Type::Char as i32,
            major: 1,
            minor: 5,
        },
        Device {
            file: format!("/dev/zero"),
            id: Some(Id {
                r#type: Type::Char as i32,
                major: 1,
                minor: 5,
            }),
            permissions: 0,
            user: 0,
            group: 0,
            read_access: true,
            write_access: true,
        },
    );
    map.insert(
        Id {
            r#type: Type::Char as i32,
            major: 1,
            minor: 7,
        },
        Device {
            file: format!("/dev/full"),
            id: Some(Id {
                r#type: Type::Char as i32,
                major: 1,
                minor: 7,
            }),
            permissions: 0,
            user: 0,
            group: 0,
            read_access: true,
            write_access: true,
        },
    );
    map.insert(
        Id {
            r#type: Type::Char as i32,
            major: 1,
            minor: 8,
        },
        Device {
            file: format!("/dev/random"),
            id: Some(Id {
                r#type: Type::Char as i32,
                major: 1,
                minor: 8,
            }),
            permissions: 0,
            user: 0,
            group: 0,
            read_access: true,
            write_access: true,
        },
    );
    map.insert(
        Id {
            r#type: Type::Char as i32,
            major: 1,
            minor: 9,
        },
        Device {
            file: format!("/dev/urandom"),
            id: Some(Id {
                r#type: Type::Char as i32,
                major: 1,
                minor: 9,
            }),
            permissions: 0,
            user: 0,
            group: 0,
            read_access: true,
            write_access: true,
        },
    );
    map.insert(
        Id {
            r#type: Type::Char as i32,
            major: 5,
            minor: 2,
        },
        Device {
            file: format!("ptmx"),
            id: Some(Id {
                r#type: Type::Char as i32,
                major: 5,
                minor: 2,
            }),
            permissions: 0,
            user: 0,
            group: 0,
            read_access: true,
            write_access: true,
        },
    );
    map.insert(
        Id {
            r#type: Type::Char as i32,
            major: 5,
            minor: 0,
        },
        Device {
            file: format!("/dev/tty"),
            id: Some(Id {
                r#type: Type::Char as i32,
                major: 5,
                minor: 0,
            }),
            permissions: 0,
            user: 0,
            group: 0,
            read_access: true,
            write_access: true,
        },
    );
    map.insert(
        Id {
            r#type: Type::Char as i32,
            major: 4,
            minor: 0,
        },
        Device {
            file: format!("/dev/tty0"),
            id: Some(Id {
                r#type: Type::Char as i32,
                major: 4,
                minor: 0,
            }),
            permissions: 0,
            user: 0,
            group: 0,
            read_access: true,
            write_access: true,
        },
    );
    map.insert(
        Id {
            r#type: Type::Char as i32,
            major: 4,
            minor: 1,
        },
        Device {
            file: format!("/dev/tty1"),
            id: Some(Id {
                r#type: Type::Char as i32,
                major: 4,
                minor: 1,
            }),
            permissions: 0,
            user: 0,
            group: 0,
            read_access: true,
            write_access: true,
        },
    );
    map.insert(
        Id {
            r#type: Type::Char as i32,
            major: 10,
            minor: 200,
        },
        Device {
            file: format!("/dev/net/tun"),
            id: Some(Id {
                r#type: Type::Char as i32,
                major: 10,
                minor: 200,
            }),
            permissions: 0,
            user: 0,
            group: 0,
            read_access: true,
            write_access: true,
        },
    );
    map.insert(
        Id {
            r#type: Type::Char as i32,
            major: 10,
            minor: 183,
        },
        Device {
            file: format!("/dev/hwrng"),
            id: Some(Id {
                r#type: Type::Char as i32,
                major: 10,
                minor: 183,
            }),
            permissions: 0,
            user: 0,
            group: 0,
            read_access: true,
            write_access: true,
        },
    );
    map.insert(
        Id {
            r#type: Type::Char as i32,
            major: 0,
            minor: 0,
        },
        Device {
            file: format!(""),
            id: Some(Id {
                r#type: Type::Char as i32,
                major: 0,
                minor: 0,
            }),
            permissions: 0,
            user: 0,
            group: 0,
            read_access: true,
            write_access: true,
        },
    );

    map
});

// Additional whitelist for unprivileged container
pub static DEV_WHITELIST_UNPRIVILEGED: Lazy<HashMap<device::Id, device::Device>> =
    Lazy::new(|| {
        use crate::c_config::device::*;
        let mut map = HashMap::new();
        map.insert(
            Id {
                r#type: Type::Char as i32,
                major: 10,
                minor: 229,
            },
            Device {
                file: format!("/dev/fuse"),
                id: Some(Id {
                    r#type: Type::Char as i32,
                    major: 10,
                    minor: 229,
                }),
                permissions: 0,
                user: 0,
                group: 0,
                read_access: true,
                write_access: true,
            },
        );

        map
    });
